package com.kinescope.app

import android.content.Context
import android.webkit.CookieManager
import java.io.File

/**
 * Patch 37: Kinescope's optional Instagram session, the sibling of [YouTubeAuth].
 *
 * Instagram no longer serves most Reels to an anonymous yt-dlp (the current extractor needs
 * browser TLS impersonation, which the bundled youtubedl-android does not ship), so downloads use
 * a normal signed-in web session instead. The user signs in on instagram.com in a private
 * WebView; the resulting `instagram.com` cookies are written once to a Netscape cookie file
 * inside the app sandbox and handed to yt-dlp's standard `--cookies` option. No password is ever
 * seen or stored, and no custom extraction is involved.
 *
 * Differences from [YouTubeAuth] that matter:
 * - Capture never deletes a saved session, and nothing re-captures before a download: yt-dlp
 *   rewrites the cookie file itself when Instagram rotates a cookie, and a re-capture would
 *   overwrite those newer values with the WebView's older ones.
 * - Sign-out removes only the instagram.com cookies from the WebView jar, never the YouTube ones.
 */
object InstagramAuth {
    private const val COOKIE_FILE_NAME = "instagram-cookies.txt"
    private const val PREFS_NAME = "instagram_auth"
    private const val KEY_AUTHENTICATED = "authenticated"
    private const val INSTAGRAM_URL = "https://www.instagram.com/"
    private const val SESSION_COOKIE = "sessionid"

    data class CaptureResult(val cookieCount: Int, val looksSignedIn: Boolean)

    fun cookieFile(context: Context): File = File(context.filesDir, COOKIE_FILE_NAME)

    fun hasSavedSession(context: Context): Boolean =
        prefs(context).getBoolean(KEY_AUTHENTICATED, false) &&
            cookieFile(context).let { it.exists() && it.length() > 32L }

    /** Captures the WebView's instagram.com cookies; a jar without `sessionid` changes nothing. */
    fun captureCurrentSession(context: Context): CaptureResult {
        val manager = CookieManager.getInstance()
        manager.flush()
        val cookies = parseCookies(manager.getCookie(INSTAGRAM_URL).orEmpty())
        val looksSignedIn = cookies.any { it.first == SESSION_COOKIE && it.second.isNotBlank() }
        if (!looksSignedIn) {
            AppLog.w("InstagramAuth", "capture found no session cookie n=${cookies.size}")
            return CaptureResult(cookies.size, false)
        }
        writeCookieFile(context, cookies)
        prefs(context).edit().putBoolean(KEY_AUTHENTICATED, true).apply()
        AppLog.i("InstagramAuth", "captured session n=${cookies.size}")
        return CaptureResult(cookies.size, true)
    }

    fun clearSession(context: Context, onDone: (() -> Unit)? = null) {
        cookieFile(context).delete()
        prefs(context).edit().clear().apply()
        val left = expireWebViewCookies()
        AppLog.i("InstagramAuth", "session cleared webview_left=$left")
        onDone?.invoke()
    }

    /**
     * CookieManager has no remove-by-domain call, so every instagram.com cookie is expired by
     * name (host-only and domain variants). Returns how many cookies the jar still reports.
     */
    private fun expireWebViewCookies(): Int {
        val manager = CookieManager.getInstance()
        parseCookies(manager.getCookie(INSTAGRAM_URL).orEmpty()).forEach { (name, _) ->
            for (domain in listOf("", "; Domain=.instagram.com", "; Domain=instagram.com")) {
                manager.setCookie(
                    INSTAGRAM_URL,
                    "$name=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/$domain"
                )
            }
        }
        manager.flush()
        return parseCookies(manager.getCookie(INSTAGRAM_URL).orEmpty()).size
    }

    private fun parseCookies(raw: String): List<Pair<String, String>> =
        raw.split(';')
            .map { it.trim() }
            .filter { it.contains('=') }
            .mapNotNull { part ->
                val split = part.indexOf('=')
                if (split <= 0) null else part.substring(0, split) to part.substring(split + 1)
            }
            .distinctBy { it.first }

    private fun writeCookieFile(context: Context, cookies: List<Pair<String, String>>) {
        val target = cookieFile(context)
        val temp = File(target.parentFile, "$COOKIE_FILE_NAME.tmp")
        temp.bufferedWriter().use { out ->
            out.appendLine("# Netscape HTTP Cookie File")
            out.appendLine("# Generated by Kinescope from its private Instagram WebView session.")
            cookies.forEach { (name, value) ->
                if (name.none { it == '\t' || it == '\n' || it == '\r' } &&
                    value.none { it == '\t' || it == '\n' || it == '\r' }
                ) {
                    out.appendLine(".instagram.com\tTRUE\t/\tTRUE\t0\t$name\t$value")
                }
            }
        }
        if (!temp.renameTo(target)) {
            target.delete()
            temp.renameTo(target)
        }
    }

    private fun prefs(context: Context) =
        context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
}
