package com.kinescope.app

import android.content.Context
import android.webkit.CookieManager
import java.io.File

/**
 * Bridges Kinescope's private WebView session to yt-dlp's standard
 * Netscape cookie-file input. No Google OAuth token is created or
 * stored. The user signs in on youtube.com and the resulting YouTube
 * cookies remain inside the app sandbox.
 */
object YouTubeAuth {
    private const val COOKIE_FILE_NAME = "youtube-cookies.txt"
    private const val PREFS_NAME = "youtube_auth"
    private const val KEY_AUTHENTICATED = "authenticated"
    private const val KEY_USER_AGENT = "user_agent"
    private const val YOUTUBE_URL = "https://www.youtube.com/"

    data class CaptureResult(val cookieCount: Int, val looksSignedIn: Boolean)

    fun cookieFile(context: Context): File = File(context.filesDir, COOKIE_FILE_NAME)

    fun hasSavedSession(context: Context): Boolean =
        prefs(context).getBoolean(KEY_AUTHENTICATED, false) &&
            cookieFile(context).let { it.exists() && it.length() > 32L }

    fun userAgent(context: Context): String? =
        prefs(context).getString(KEY_USER_AGENT, null)?.takeIf { it.isNotBlank() }

    /**
     * Captures the latest WebView cookies. Calling this immediately
     * before a download also refreshes the file if YouTube rotated a
     * cookie after the user originally signed in.
     */
    fun captureCurrentSession(context: Context, userAgent: String? = null): CaptureResult {
        val manager = CookieManager.getInstance()
        manager.flush()
        val cookies = parseCookies(manager.getCookie(YOUTUBE_URL).orEmpty())
        val names = cookies.map { it.first }.toSet()
        val looksSignedIn = names.any { it in AUTH_COOKIE_NAMES }
        val prefs = prefs(context)

        if (!userAgent.isNullOrBlank()) {
            prefs.edit().putString(KEY_USER_AGENT, userAgent).apply()
        }

        if (cookies.isEmpty() || !looksSignedIn) {
            cookieFile(context).delete()
            prefs.edit().putBoolean(KEY_AUTHENTICATED, false).apply()
            AppLog.w(
                "YouTubeAuth",
                "YouTube cookie capture did not contain authenticated session markers; cookies=${cookies.size}"
            )
            return CaptureResult(cookies.size, false)
        }

        writeCookieFile(context, cookies)
        prefs.edit().putBoolean(KEY_AUTHENTICATED, true).apply()
        AppLog.i("YouTubeAuth", "Captured authenticated YouTube session cookies=${cookies.size}")
        return CaptureResult(cookies.size, true)
    }

    /** Refreshes an already-saved session from WebView's persistent cookie store. */
    fun refreshSavedSession(context: Context): Boolean {
        if (!prefs(context).getBoolean(KEY_AUTHENTICATED, false)) return false
        return captureCurrentSession(context).looksSignedIn
    }

    fun clearSession(context: Context, onDone: (() -> Unit)? = null) {
        cookieFile(context).delete()
        prefs(context).edit().clear().apply()
        CookieManager.getInstance().removeAllCookies {
            CookieManager.getInstance().flush()
            AppLog.i("YouTubeAuth", "YouTube WebView session cleared")
            onDone?.invoke()
        }
    }

    private fun parseCookies(raw: String): List<Pair<String, String>> =
        raw.split(';')
            .map { it.trim() }
            .filter { it.contains('=') }
            .mapNotNull { part ->
                val split = part.indexOf('=')
                if (split <= 0) null else part.substring(0, split) to part.substring(split + 1)
            }
            .distinctBy { it.first }

    private fun writeCookieFile(context: Context, cookies: List<Pair<String, String>>) {
        cookieFile(context).bufferedWriter().use { out ->
            out.appendLine("# Netscape HTTP Cookie File")
            out.appendLine("# Generated by Kinescope from its private YouTube WebView session.")
            cookies.forEach { (name, value) ->
                out.appendLine(".youtube.com\tTRUE\t/\tTRUE\t0\t$name\t$value")
            }
        }
    }

    private fun prefs(context: Context) =
        context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    private val AUTH_COOKIE_NAMES = setOf(
        "SAPISID",
        "APISID",
        "SID",
        "SSID",
        "LOGIN_INFO",
        "__Secure-1PSID",
        "__Secure-3PSID",
        "__Secure-1PSIDTS",
        "__Secure-3PSIDTS"
    )
}
